### ISSUE TITLE
Not building in esphome 2025.2.0

### ISSUE THREAD

**Issue by stevenwfoley** [staiji/esphome-lgtv_uart#5]
I realize this is an old repository, and I'm not sure if you're still maintaining, but I'm wondering if you'd be willing to make some updates?
Esphome 2025.2.0 implemented two breaking changes that effect the building of this project:
https://github.com/esphome/esphome/pull/8118
https://github.com/esphome/esphome/pull/8119

The deprecated esphome "platform" configuration change in 8118 is an easy fix, but the conversion of "custom" component to external_components in 8119 is outside my wheelhouse.

Thanks for your consideration!

**Comment by kw4tts** [comment]
(edit: disclamer: i have been using this project for quite some time)

Have a go with this yaml:

- zero need for external components
- zero need for existing lgtv_uart.h
- works with built-in lambda on UART RX,
- compiles fast. :)

I have plagiarised [UARTDebug::log_string](https://api-docs.esphome.io/uart__debugger_8cpp_source) for this. And _I know_ this doesn't fit well with the "don't repeat yourself" pragma. But it is a hacky, fast, and esphome-native solution.

I have also added the "mute"/"power" settings _as a switch_ rather than as a button (just my cup of tea. 🤷 and helps with HomeAssistant automations as well)

@staiji if you consider this to be an OK workaround, maybe commit it to the repo.

---

```yaml
substitutions:
  name: esp-lg-tv
  friendly_name: ESP-LG-TV
  upper_devicename: LG TV

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: upesy_wroom
  framework:
    type: esp-idf

logger:
api:
  encryption:
    key: !secret api_encryption
ota:
  platform: esphome
  password: !secret ota_psk
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${name}"
    password: !secret wifi_ap_psk

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor - ${name}"
    update_interval: 60s
  - platform: uptime
    name: "Uptime Sensor - ${name}"

uart:
  id: uart_bus
  baud_rate: 9600
  tx_pin: 17
  rx_pin: 16
  debug:
    direction: "RX"
    dummy_receiver: True
    sequence:
      - lambda: |-
          //UARTDebug::log_string(direction, bytes); 
          std::string res;
          size_t len = bytes.size();
          char buf[5];
          for (size_t i = 0; i < len; i++) {
            if (bytes[i] == 10) {
            //  res += "\\n";
            // skip the "\n" displaying
            } else if (bytes[i] == 13) {
            //  res += "\\r";
            // skip the "\r" displaying
            } else if (bytes[i] < 32 || bytes[i] > 127) {
              sprintf(buf, "\\x%02X", bytes[i]);
              res += buf;
            } else {
              res += bytes[i];
            }
          }
          id(power).publish_state(res.c_str());

interval:
  - interval: 5s
    then:
      - uart.write: "ka 00 ff\r"
    
binary_sensor:
  - platform: gpio
    pin: 
      number: 23
      mode:
        input: true
        pulldown: true
    name: "TV desired state"

text_sensor:
  - platform: template
    id: "power"

switch:
  - platform: template
    name: "${upper_devicename}"
    icon: mdi:television
    restore_mode: DISABLED
    lambda: |-
      if(id(power).state == "A 01 OK01x"){
        return true;
      }
      else {if (id(power).state == "A 01 OK00x"){
        return false;
      } else {return {};}}
    turn_on_action:
      - button.press: tvon_switch
    turn_off_action:
      - button.press: tvoff_switch

  - platform: template
    name: "${upper_devicename} mute"
    icon: mdi:television
    turn_on_action:
      - button.press: tvmute_switch
    turn_off_action:
      - button.press: tvunmute_switch

button:
  - platform: uart
    name: "${upper_devicename} Off"
    id: tvoff_switch
    internal: true
    disabled_by_default: true
    data: "ka 00 00\r"
    icon: mdi:television-off
  - platform: uart
    name: "${upper_devicename} On"
    id: tvon_switch
    internal: true
    disabled_by_default: true
    data: "ka 00 01\r"
    icon: mdi:television
  - platform: uart
    name: "${upper_devicename} Mute"
    internal: true
    disabled_by_default: true
    data: "ke 00 00\r"
    icon: mdi:volume-off
    id: tvmute_switch
  - platform: uart
    name: "${upper_devicename} Unmute"
    internal: true
    disabled_by_default: true
    icon: mdi:volume-high
    data: "ke 00 01\r"
    id: tvunmute_switch
  - platform: uart
    name: "${upper_devicename} DTV"
    data: "xb 00 01\r"
  - platform: uart
    name: "${upper_devicename} HDMI1"
    data: "xb 00 90\r"
    icon: mdi:video-input-hdmi
  - platform: uart
    name: "${upper_devicename} HDMI2"
    data: "xb 00 91\r"
    icon: mdi:video-input-hdmi
  - platform: uart
    name: "${upper_devicename} HDMI3"
    data: "xb 00 92\r"
    icon: mdi:video-input-hdmi
  - platform: uart
    name: "${upper_devicename} HDMI4"
    data: "xb 00 93\r"
    icon: mdi:video-input-hdmi
  - platform: uart
    name: "${upper_devicename} Vol10"
    data: "kf 00 0a\r"
    icon: mdi:volume-low
  - platform: uart
    name: "${upper_devicename} Vol20"
    data: "kf 00 14\r"
    icon: mdi:volume-medium
  - platform: uart
    name: "${upper_devicename} Vol40"
    data: "kf 00 28\r"
    icon: mdi:volume-medium
  - platform: uart
    name: "${upper_devicename} Vol50"
    #data: "kf 00 05\r" #vol5
    data: "kf 00 32 \r"
    icon: mdi:volume-high
  - platform: uart
    name: "${upper_devicename} Vol60"
    data: "kf 00 3c\r"
    icon: mdi:volume-high
  - platform: uart
    name: "${upper_devicename} OK"
    data: "mc 00 44\r"
    icon: mdi:check-circle
  - platform: uart
    name: "${upper_devicename} Vol Up"
    data: "mc 00 02\r"
    icon: mdi:volume-plus
  - platform: uart
    name: "${upper_devicename} Vol Down"
    data: "mc 00 03\r"
    icon: mdi:volume-minus
  - platform: uart
    name: "${upper_devicename} CH Up"
    data: "mc 00 00\r"
    icon: mdi:chevron-up
  - platform: uart
    name: "${upper_devicename} CH Down"
    data: "mc 00 01\r"
    icon: mdi:chevron-down
  - platform: uart
    name: "${upper_devicename} SBS"
    data: "ma 00 00 00 06 00 01 26\r"
  - platform: uart
    name: "${upper_devicename} KBS2"
    data: "ma 00 00 00 07 00 01 26\r"
  - platform: uart
    name: "${upper_devicename} KBS1"
    data: "ma 00 00 00 09 00 01 26\r"
  - platform: uart
    name: "${upper_devicename} MBC"
    data: "ma 00 00 00 0b 00 01 26\r"
  - platform: uart
    name: "${upper_devicename} EBS1"
    data: "ma 00 00 00 0a 00 01 26\r"
  - platform: uart
    name: "${upper_devicename} EBS2"
    data: "ma 00 00 00 0a 00 02 26\r"
```
